package metier;
// Generated 12 mars 2013 16:04:39 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private Adherent adherent;
     private Oeuvrevente oeuvrevente;
     private Date dateReservation;
     private String statut;

    public Reservation() {
    }

    public Reservation(ReservationId id, Adherent adherent, Oeuvrevente oeuvrevente, Date dateReservation, String statut) {
       this.id = id;
       this.adherent = adherent;
       this.oeuvrevente = oeuvrevente;
       this.dateReservation = dateReservation;
       this.statut = statut;
    }
   
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    public Adherent getAdherent() {
        return this.adherent;
    }
    
    public void setAdherent(Adherent adherent) {
        this.adherent = adherent;
    }
    public Oeuvrevente getOeuvrevente() {
        return this.oeuvrevente;
    }
    
    public void setOeuvrevente(Oeuvrevente oeuvrevente) {
        this.oeuvrevente = oeuvrevente;
    }
    public Date getDateReservation() {
        return this.dateReservation;
    }
    
    public void setDateReservation(Date dateReservation) {
        this.dateReservation = dateReservation;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


